### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by gyermolenko** [hchasestevens/astpath#12]
`astpath` 0.9.0

```text
$ python -V
Python 3.8.0b1+

$ echo "x = 3" > 1.py   

$ echo "(x := 3)" > 2.py

$ astpath ".//Num"
```
No output.

With Python 3.7 output for same files is 
```
$ astpath ".//Num"
./1.py:0    >	x = 3
```

**Comment by hchasestevens** [comment]
Hi @gyermolenko , thanks for the question. Unfortunately, in Python 3.8, the internal AST representation has undergone backwards-incompatible breaking changes. The new node corresponding to both `Num` and `Str` (possibly others as well) is `Constant`, as can be seen here:
```bash
root@8d7a11811a92:/test# python -V
Python 3.8.0b1
root@8d7a11811a92:/test# echo "x = 3" > 1.py
root@8d7a11811a92:/test# echo "(x := 3)" > 2.py
root@8d7a11811a92:/test# astpath ".//Constant"
./2.py:0    >	(x := 3)
./1.py:0    >	x = 3
```
Specifically, this is how `1.py` looks in the AST:
```
>>> import ast
>>> ast.dump(ast.parse("x = 3"))
"Module(body=[Assign(targets=[Name(id='x', ctx=Store())], value=Constant(value=3, kind=None), type_comment=None)], type_ignores=[])"
```
The best way I know of disambiguating these cases is to perform a test on the `@value` attribute of the `Constant`, as explained here: https://stackoverflow.com/a/3857478/766812
```
root@8d7a11811a92:/test# echo "x = 'hello world'" > 3.py
root@8d7a11811a92:/test# astpath ".//Constant[number(@value) = number(@value)]"
./2.py:0    >	(x := 3)
./1.py:0    >	x = 3
root@8d7a11811a92:/test# astpath ".//Constant"
./2.py:0    >	(x := 3)
./3.py:0    >	x = 'hello world'
./1.py:0    >	x = 3
```

Hope this helps, and thanks again for reaching out!

**Comment by gyermolenko** [comment]
wow, thanks a lot for explanation!

So python changes in AST are not in scope of this library. It is a matter of "xpath-like expression" which should be tuned in user's code depending on what he wants.
Did I understand you properly?

Somehow related:
lxml-4.3.4 was released 3 days ago with [this fix](https://bugs.launchpad.net/lxml/+bug/1829853) for python3.8-related issue.

**Comment by hchasestevens** [comment]
Yes @gyermolenko, your understanding is correct. Authors of expressions must target them to the specific Python AST version they would like to search through, `astpath` is agnostic. It just happens that for most of the versions from 2.7 though 3.7 the changes to the AST representation have been minimal/mostly additive. I think that the lxml ticket you link is related to C bindings in Cython ( https://en.m.wikipedia.org/wiki/Cython ) which is not pertinent to the issue you posted per se.

**Comment by danihodovic** [comment]
@hchasestevens Do you think this library will be updated in the future for python 3.8 support?

**Comment by hchasestevens** [comment]
Hi @danihodovic - it should already be Python 3.8 compatible (see below). If you believe there are specific issues, please raise a ticket.

```python
λ docker run --rm -it python:3.8 bash
root@c56093ab0b59:/# pip install astpath[xpath]
Collecting astpath[xpath]
  Downloading astpath-0.9.0.tar.gz (7.1 kB)
Collecting lxml>=3.3.5
  Downloading lxml-4.5.0-cp38-cp38-manylinux1_x86_64.whl (5.6 MB)
     |████████████████████████████████| 5.6 MB 5.3 MB/s
Building wheels for collected packages: astpath
  Building wheel for astpath (setup.py) ... done
  Created wheel for astpath: filename=astpath-0.9.0-py3-none-any.whl size=6058 sha256=b77028451bea0dd8a87fa610b1666cd44e6a4269e7f5d5dc8b184b361b764731
  Stored in directory: /root/.cache/pip/wheels/9d/99/20/6ff72219693819ecf8685024a047a88115170e0b18aeeddcf0
Successfully built astpath
Installing collected packages: lxml, astpath
Successfully installed astpath-0.9.0 lxml-4.5.0
root@c56093ab0b59:/# cd /usr/local/lib/python3.8
root@c56093ab0b59:/usr/local/lib/python3.8# astpath ".//FunctionDef" | head -5
./webbrowser.py:21   >  def register(name, klass, instance=None, *, preferred=False):
./webbrowser.py:36   >  def get(using=None):
./webbrowser.py:70   >  def open(url, new=0, autoraise=True):
./webbrowser.py:81   >  def open_new(url):
./webbrowser.py:84   >  def open_new_tab(url):
```
