### ISSUE TITLE
how to search in class basses for class hierarchy? 

### ISSUE THREAD

**Issue by shrhawk-entertainer** [hchasestevens/astpath#16]
I want to search for subclasses of a class as below:

```
from testing_classes import Child, Parent

class test(Child):
    def __init__(self):
        pass

    def child_method(self):
        print('child')

    def child_class_method(self):
        print('child class method')

class test2(Child):
    def __init__(self):
        pass

    def child_method(self):
        print('child')

    def child_class_method(self):
        print('child class method')
```

Using the following xpath expression but no result
`>>> astpath "//ClassDef/bases[contains(@id, 'Child')]" `

Please  guide me on how to achieve this, also its better if we have a list of more examples for the beginners

**Comment by gyermolenko** [comment]
try this one 
`$ astpath ".//ClassDef/bases/Name[contains(@id, 'Base')]"`

**Comment by shrhawk-entertainer** [comment]
thanks, @gyermolenko can you give example for class override methods also?

**Comment by gyermolenko** [comment]
Nope, sorry. 

Maybe check `Class.mro()` first (from regular python code) and for each node look for a specific `FunctionDef.name`? 🤷
